services:
  mysql:
    image: mysql:8.0
    container_name: qlbaotri_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: qlbaotri
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
